[package]
name = "service"
version = "0.1.0"
authors = ["bkspace <sammyisseyegh@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lp-modeler = "0.4.2"
